'use strict';

/**
 * Draws the app icon and writes build/icon.png plus a multi-size build/icon.ico.
 *
 * Written against zlib alone so the project needs no image dependency: the raster
 * is generated by hand, encoded as PNG, and the ICO is a container around PNGs.
 *
 * The mark is the same gauge the widget is built around — a 270° dial with a clay
 * sweep — so the icon and the interface say the same thing.
 */

const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const BUILD_DIR = path.join(__dirname, '..', 'build');

const TILE = [0x24, 0x1b, 0x17, 0xff];
const TRACK = [0x4a, 0x3a, 0x33, 0xff];
const CLAY = [0xd9, 0x77, 0x57, 0xff];

const START_ANGLE = (3 * Math.PI) / 4; // bottom-left
const SWEEP = (3 * Math.PI) / 2; // 270°
const FILL = 0.68;
const SAMPLES = 3; // supersampling grid per axis

/* ------------------------------------------------------------------ drawing */

function sampleColor(x, y, size) {
  const radius = size * 0.22;
  const max = size - 1;

  // Rounded-square tile: outside the corner radius the pixel is transparent.
  const cornerX = Math.min(x, max - x);
  const cornerY = Math.min(y, max - y);
  if (cornerX < radius && cornerY < radius) {
    const dx = radius - cornerX;
    const dy = radius - cornerY;
    if (Math.hypot(dx, dy) > radius) return null;
  }

  const cx = max / 2;
  const cy = max / 2;
  const dist = Math.hypot(x - cx, y - cy);
  const outer = size * 0.375;
  const inner = size * 0.255;

  if (dist > outer || dist < inner) return TILE;

  // Screen coordinates put y downward, so increasing angle runs clockwise.
  const angle = Math.atan2(y - cy, x - cx);
  let travelled = angle - START_ANGLE;
  while (travelled < 0) travelled += Math.PI * 2;

  if (travelled > SWEEP) return TILE; // the dial's open gap at the bottom
  return travelled <= SWEEP * FILL ? CLAY : TRACK;
}

function raster(size) {
  const pixels = Buffer.alloc(size * size * 4);
  const step = 1 / SAMPLES;

  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      let r = 0;
      let g = 0;
      let b = 0;
      let a = 0;

      for (let sy = 0; sy < SAMPLES; sy++) {
        for (let sx = 0; sx < SAMPLES; sx++) {
          const color = sampleColor(x + (sx + 0.5) * step, y + (sy + 0.5) * step, size);
          if (!color) continue;
          r += color[0];
          g += color[1];
          b += color[2];
          a += color[3];
        }
      }

      const total = SAMPLES * SAMPLES;
      const offset = (y * size + x) * 4;
      const alpha = a / total;

      // Store straight (unpremultiplied) colour, averaged over covered samples only.
      const covered = a === 0 ? 1 : a / 255;
      pixels[offset] = Math.round(r / covered);
      pixels[offset + 1] = Math.round(g / covered);
      pixels[offset + 2] = Math.round(b / covered);
      pixels[offset + 3] = Math.round(alpha);
    }
  }

  return pixels;
}

/* ------------------------------------------------------------- PNG encoding */

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = 0xffffffff;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function encodePng(pixels, size) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(size, 0);
  ihdr.writeUInt32BE(size, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // truecolour with alpha
  ihdr[10] = 0;
  ihdr[11] = 0;
  ihdr[12] = 0;

  const stride = size * 4;
  const raw = Buffer.alloc((stride + 1) * size);
  for (let y = 0; y < size; y++) {
    raw[y * (stride + 1)] = 0; // filter type: none
    pixels.copy(raw, y * (stride + 1) + 1, y * stride, (y + 1) * stride);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

/* ------------------------------------------------------------- ICO encoding */

function encodeIco(entries) {
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2); // 1 = icon
  header.writeUInt16LE(entries.length, 4);

  const directory = Buffer.alloc(16 * entries.length);
  let offset = header.length + directory.length;

  entries.forEach((entry, index) => {
    const at = index * 16;
    directory[at] = entry.size >= 256 ? 0 : entry.size; // 0 stands for 256
    directory[at + 1] = entry.size >= 256 ? 0 : entry.size;
    directory[at + 2] = 0;
    directory[at + 3] = 0;
    directory.writeUInt16LE(1, at + 4); // colour planes
    directory.writeUInt16LE(32, at + 6); // bits per pixel
    directory.writeUInt32LE(entry.png.length, at + 8);
    directory.writeUInt32LE(offset, at + 12);
    offset += entry.png.length;
  });

  return Buffer.concat([header, directory, ...entries.map((entry) => entry.png)]);
}

/* --------------------------------------------------------------------- main */

fs.mkdirSync(BUILD_DIR, { recursive: true });

const master = 1024;
fs.writeFileSync(path.join(BUILD_DIR, 'icon.png'), encodePng(raster(master), master));

const icoSizes = [16, 24, 32, 48, 64, 128, 256];
const entries = icoSizes.map((size) => ({ size, png: encodePng(raster(size), size) }));
fs.writeFileSync(path.join(BUILD_DIR, 'icon.ico'), encodeIco(entries));

console.log(`Wrote build/icon.png (${master}px) and build/icon.ico (${icoSizes.join(', ')}px)`);
